name: rewatcher
version: 0.0.1
description: A fast CLI tool for watching and rerunning
author: just nobody
homepage: https://github.com/just-nobody/rewatcher

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  args: '>=0.10.0 <0.14.0'
